title: Stel de pinnen in voor een RGB-LED
hero_image: images/banner.png
description: Stel de pinnen voor een RGB-LED in MicroPython in met de Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - 
    title: Stel de pinnen in voor een RGB-LED
