---
title: Définir les broches pour une LED RVB
hero_image: images/banner.png
description: Définir les broches d'une LED RVB en MicroPython avec le Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - title: Définir les broches pour une LED RVB
